<?php
/**
 * Implements hook_page_menu().
 */
function remember_ltrv_menu() {
    $items = array();

    $items['admin/config/user-interface/remember_ltrv'] = array(
        'title'            => 'LAST SELECTION',
        'description'      => 'Administer remember_ltrv settings',
        'page callback'    => 'drupal_get_form',
        'page arguments'   => array('remember_ltrv_settings'),
        'access arguments' => array('Administer site configuration '),
        'file'             => 'remember_ltrv.admin.inc',
        'type'             => MENU_NORMAL_ITEM,
    );

    return $items;
}

function remember_ltrv_form_alter(&$form, &$form_state, $form_id) {
    global $user;
    if($form_id == 'taxonomy_form_term') {
        if(in_array('administrator', $user->roles)) {
            if(strpos($form['#action'], 'taxonomy/'.variable_get('remember_ltrv_vocabulary', 'tags').'/add') != false) {
                //$last_selection = variable_get('last_selection', array(0 => 0));
                //print_r(variable_get('last_selection', array(0 => 0)));
                $form["relations"]["parent"]["#default_value"] = variable_get('last_selection', array(0 => 0));

                $form['#submit'][] = 'save_last_relations_value';
            }
        }
    }

}

function save_last_relations_value(&$form, &$form_state) {

    if(isset($form_state["values"]["parent"])) {
        if(count($form_state["values"]["parent"]) == 0) {
            variable_set('last_selection', array(0 => 0));
        } else {
            variable_set('last_selection', $form_state["values"]["parent"]);
        }

    }
}

